### ISSUE TITLE
You can earn rewards by killing yourself

### ISSUE THREAD

**Issue by Redwolf223** [Patrick260/Kill-Rewards-Plugin#2]
**Describe the bug**\
You can earn money by killing yourself

**To Reproduce**\
Kill yourself on Minecraft

**Expected behavior**\
For the reward not to be given when a player kills himself

**Screenshots**\

**Additional context**\

**Comment by Redwolf223** [comment]
Hello, any update?

**Comment by Patrick260** [comment]
Fixed with the commits b3cf592c069a92d5da4e7d3425af3d7bdf86baab and 2cab30f08cc73ca03a2266d8a91006101d0cfd83, fix is included in the new v.1.3.4 release.
